apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkaacls.kafka.acl.io
spec:
  group: kafka.acl.io
  scope: Namespaced
  names:
    plural: kafkaacls
    singular: kafkaacl
    kind: KafkaACL
    shortNames:
      - kacl
  versions:
    - name: v1alpha1  # ✅ Corrected version name
      served: true
      storage: true  # ✅ Marking this as the stored version
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["principal", "topic", "operations"]
              properties:
                principal:
                  type: string
                  description: "Kafka principal (e.g., 'User:my-app-user')"
                topic:
                  type: string
                  description: "Kafka topic name"
                operations:
                  type: array
                  description: "List of allowed Kafka operations (Read, Write, etc.)"
                  items:
                    type: string
                    enum: ["Read", "Write", "Create", "Delete", "Alter"]
